# Generated by Django 3.0.6 on 2020-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_computer_science_dept_lab_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
    ]
