# Generated by Django 3.0.6 on 2020-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_computer_science_dept_major_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='Regular Event', max_length=500)),
            ],
        ),
    ]
