# Generated by Django 3.0.6 on 2020-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_computer_science_dept_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='Staff Achievement', max_length=500)),
            ],
        ),
    ]
