# Generated by Django 3.0.6 on 2020-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_computer_science_dept_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_achievements',
            name='achievement_type',
            field=models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500),
        ),
        migrations.AlterField(
            model_name='computer_science_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500),
        ),
    ]
